### ISSUE TITLE
Revert nextjournal.log to re-frame.loggers

### ISSUE THREAD

**Issue by clyfe** [nextjournal/freerange#11]
Would you folks consider reverting nextjournal.log to re-frame.loggers in re-frame.registry, so it can be consumed by others too without having to make a shim? Also upstream re-frame re-frame.registry is now named re-frame.registrar, I'd be interested in a match.

**Comment by mk** [comment]
Hi @clyfe,

Sorry for the eternal silence, we finally took care of dropping the `nextjournal.log` dependency.

The registry / registrar naming dates back to 45b801a6492b1ea0aaa61955e7e1e6c99dbf49b5 and 7242560970df63c27ca61ae5a6e95403906402e9. Feel free to open a separate issue enumerating what parts of the api you're using there.

Best,
Martin
